apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::176452453024:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1S5M0F6K8WXLW
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::176452453024:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2023-06-11T09:46:26Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1635"
  uid: 728ab205-9c2b-46e2-aa7b-34caeb3a6abb
